theme: jekyll-theme-minimal
title: Welcome to my website! 
description: I am Marcella Scoczynski R. Martins, an Assistant Professor at Federal University of Technology - Parana, Brazil (UTFPR). My main research interests are Evolutionary Computation, Metaheuristics, Multi and many optimization problems, Estimation of Distribution Algorithms.
