theme: jekyll-theme-minimal
title: Welcome to Marcella Scoczynski website! 
description: I am an Assistant Professor at Federal University of Technology - Parana UTFPR. My main research interests are Evolutionary Computation, Metaheuristics, Multi and many optimization problems, Estimation of Distribution Algorithms.
