theme: jekyll-theme-minimal
title: Welcome to Marcella Scoczynski website! 
description: I am an Assistant Professor at Federal University of Technology - Parana UTFPR. 
Research interests: Evolutionary Computation, Metaheuristics, Multi and many optimization problems, Estimation of Distribution Algorithms.
